# Terraform and provider version constraints.
#
# Authentication uses a short-lived GitHub App installation token generated by
# actions/create-github-app-token in the CI workflow.  The orchestration script
# (scripts/create_repo.sh) exports TF_VAR_github_token from the
# REPO_AUTOMATION_TOKEN environment variable.

terraform {
  required_version = ">= 1.14"

  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 6.0"
    }
  }
}

provider "github" {
  owner = var.github_owner
  token = var.github_token
}
