name: "On PR & push: Lint Workflows"

on:
  push:
    paths:
      - .github/workflows/**
  pull_request:
    paths:
      - .github/workflows/**

jobs:
  actionlint:
    name: Lint GitHub Actions workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Check workflow files
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color
